# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 22 Nov 2012 07:17:04 +0000
*       @user   1
*       @ALL    0
