<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Tue, 29 Oct 2013 11:58:29 +0100
 */

$conf['title'] = 'YOUR dokuwiki';
$conf['lang'] = 'fr';
$conf['license'] = 'publicdomain';
$conf['sneaky_index'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['notify'] = 'admin@superadmin.com';
$conf['mailfrom'] = 'admin@youdokuwiki.com';
$conf['useacl']      = 1;

// end auto-generated content
